#Task 1

Загрузите датасет выполнив следующий код
from sklearn.datasets import load_wine

wine_dataset = load_wine()
Изучите документацию функции train_test_split. С ее помощью датасет можно разделить на тренировочную и тестовую выборки. Первая нужна для обучения модели, а вторая - для оценки качества модели.

Разделите wine_dataset на обучающую и тестовую выборки.

Обучите модель на тренировочной выборке и оцените ее качество на тестовой.

Попробуйте повторить шаги 3 и 4 разбив датасет на обучающую и тестовую выборки в какой-то собственной пропорции. Как это отразилось на качестве модели?

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression, RidgeClassifier, LinearRegression
from sklearn.metrics import confusion_matrix, f1_score, accuracy_score, mean_absolute_error as MAE, mean_squared_error as MSE, r2_score, accuracy_score
from sklearn.datasets import load_wine

In [2]:
wine_dataset = load_wine()
X = pd.DataFrame(data=wine_dataset.data, columns=wine_dataset.feature_names)
X.head()

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0    14.23        1.71  2.43               15.6      127.0           2.80   
1    13.20        1.78  2.14               11.2      100.0           2.65   
2    13.16        2.36  2.67               18.6      101.0           2.80   
3    14.37        1.95  2.50               16.8      113.0           3.85   
4    13.24        2.59  2.87               21.0      118.0           2.80   

   flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   
3        3.49                  0.24             2.18             7.80  0.86   
4        2.69                  0.39             1.82             4.32  1.04   

   od280/od315_of_diluted_wines  proline  
0                          3.92   1065.0  
1                          3.40   1050.0  
2                          3.17   1185.0  
3                          3.45   1480.0  
4                          2.93    735.0

In [3]:
Y = np.array(wine_dataset.target)
Y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2])

In [4]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.2, random_state=0)
model = RidgeClassifier()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
compare_df = pd.DataFrame({'y_pred': y_pred, 'y_test': y_test})
print(compare_df)
print(f'confusion_matrix : \n {confusion_matrix(y_test,y_pred)}')
print(f'accuracy_score : {accuracy_score(y_test,y_pred)*100}%')

    y_pred  y_test
0        0       0
1        2       2
2        1       1
3        0       0
4        1       1
5        1       1
6        0       0
7        2       2
8        1       1
9        1       1
10       2       2
11       2       2
12       0       0
13       1       1
14       2       2
15       1       1
16       0       0
17       0       0
18       1       1
19       0       0
20       1       1
21       0       0
22       0       0
23       1       1
24       1       1
25       1       1
26       1       1
27       1       1
28       1       1
29       2       2
30       0       0
31       0       0
32       1       1
33       0       0
34       0       0
35       0       0
confusion_matrix : 
 [[14  0  0]
 [ 0 16  0]
 [ 0  0  6]]
accuracy_score : 100.0%


змінюємо співвідношення тестової і тренувальної вибірки

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.5, random_state=0)
model = RidgeClassifier()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
compare_df = pd.DataFrame({'y_pred': y_pred, 'y_test': y_test})
print(compare_df)
print(f'confusion_matrix : \n {confusion_matrix(y_test,y_pred)}')
print(f'accuracy_score : {accuracy_score(y_test,y_pred)*100}%')

    y_pred  y_test
0        0       0
1        2       2
2        1       1
3        0       0
4        1       1
..     ...     ...
84       2       2
85       1       1
86       1       1
87       1       1
88       1       1

[89 rows x 2 columns]
confusion_matrix : 
 [[25  0  0]
 [ 1 38  1]
 [ 0  0 24]]
accuracy_score : 97.75280898876404%


висновок: при 50/50 співвідношені результат погіршився

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.1, random_state=0)
model = RidgeClassifier()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
compare_df = pd.DataFrame({'y_pred': y_pred, 'y_test': y_test})
print(compare_df)
print(f'confusion_matrix : \n {confusion_matrix(y_test,y_pred)}')
print(f'accuracy_score : {accuracy_score(y_test,y_pred)*100}%')

    y_pred  y_test
0        0       0
1        2       2
2        1       1
3        0       0
4        1       1
5        1       1
6        0       0
7        2       2
8        1       1
9        1       1
10       2       2
11       2       2
12       0       0
13       1       1
14       2       2
15       1       1
16       0       0
17       0       0
confusion_matrix : 
 [[6 0 0]
 [0 7 0]
 [0 0 5]]
accuracy_score : 100.0%


# Task 2

Постройте линейный классификатор подобно тому, как мы это делали в задании 1 на датасете Ириса Фишера. Оформите решение в виде jupyter ноутбука.

In [7]:
from sklearn.datasets import load_iris

In [8]:
iris_data = load_iris(as_frame=True)
iris_X = iris_data.data
iris_Y = iris_data.target
iris_Y

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: target, Length: 150, dtype: int32

In [9]:
iris_X.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [10]:
iris_X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
dtypes: float64(4)
memory usage: 4.8 KB


In [11]:
iris_X.describe()

sepal length (cm)  sepal width (cm)  petal length (cm)  \
count         150.000000        150.000000         150.000000   
mean            5.843333          3.057333           3.758000   
std             0.828066          0.435866           1.765298   
min             4.300000          2.000000           1.000000   
25%             5.100000          2.800000           1.600000   
50%             5.800000          3.000000           4.350000   
75%             6.400000          3.300000           5.100000   
max             7.900000          4.400000           6.900000   

       petal width (cm)  
count        150.000000  
mean           1.199333  
std            0.762238  
min            0.100000  
25%            0.300000  
50%            1.300000  
75%            1.800000  
max            2.500000

In [12]:
X_train, X_test, y_train, y_test = train_test_split(iris_X, iris_Y, test_size = 0.2, random_state=0)
model = RidgeClassifier()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
print(f'confusion_matrix : \n {confusion_matrix(y_test,y_pred)}')
print(f'accuracy_score : {accuracy_score(y_test,y_pred)*100}%')

confusion_matrix : 
 [[11  0  0]
 [ 0  8  5]
 [ 0  1  5]]
accuracy_score : 80.0%


In [13]:
X_train, X_test, y_train, y_test = train_test_split(iris_X, iris_Y, test_size = 0.2, random_state=0)
model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
print(f'confusion_matrix : \n {confusion_matrix(y_test,y_pred)}')
print(f'accuracy_score : {accuracy_score(y_test,y_pred)*100}%')


confusion_matrix : 
 [[11  0  0]
 [ 0 13  0]
 [ 0  0  6]]
accuracy_score : 100.0%


LogisticRegression більше підходить до цього датасета ніж RidgeClassifier

# Task 3

В этом задании нам предстоит построить линейный регрессор. В этот раз мы будем работать с данными о заболевании диабетом. Аналогично заданию 1 выполните следующие шаги

Загрузите датасет.
Разделите его на тренировочную и тестовую выборки.
На тренировочной выборке обучите линейную модель.
Оцените ее качество на тестовой выборке.
Попробуйте повторить шаги 1-4 разбив датасет на обучающую и тестовую выборки в какой-то собственной пропорции. Как это отразилось на качестве модели?
Оформите решение в виде jupyter ноутбука.

In [14]:
from sklearn.datasets import load_diabetes

In [15]:
diab_data = load_diabetes(as_frame=True)
diab_X = diab_data.data
diab_Y = diab_data.target
diab_Y

0      151.0
1       75.0
2      141.0
3      206.0
4      135.0
       ...  
437    178.0
438    104.0
439    132.0
440    220.0
441     57.0
Name: target, Length: 442, dtype: float64

In [16]:
diab_X.head()

age       sex       bmi        bp        s1        s2        s3  \
0  0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1 -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2  0.085299  0.050680  0.044451 -0.005671 -0.045599 -0.034194 -0.032356   
3 -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038   
4  0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142   

         s4        s5        s6  
0 -0.002592  0.019908 -0.017646  
1 -0.039493 -0.068330 -0.092204  
2 -0.002592  0.002864 -0.025930  
3  0.034309  0.022692 -0.009362  
4 -0.002592 -0.031991 -0.046641

In [17]:
print(diab_data.DESCR)

.. _diabetes_dataset:

Diabetes dataset
----------------

Ten baseline variables, age, sex, body mass index, average blood
pressure, and six blood serum measurements were obtained for each of n =
442 diabetes patients, as well as the response of interest, a
quantitative measure of disease progression one year after baseline.

**Data Set Characteristics:**

  :Number of Instances: 442

  :Number of Attributes: First 10 columns are numeric predictive values

  :Target: Column 11 is a quantitative measure of disease progression one year after baseline

  :Attribute Information:
      - age     age in years
      - sex
      - bmi     body mass index
      - bp      average blood pressure
      - s1      tc, total serum cholesterol
      - s2      ldl, low-density lipoproteins
      - s3      hdl, high-density lipoproteins
      - s4      tch, total cholesterol / HDL
      - s5      ltg, possibly log of serum triglycerides level
      - s6      glu, blood sugar level

Note: Each of these 1

In [18]:
diab_X.describe()

age           sex           bmi            bp            s1  \
count  4.420000e+02  4.420000e+02  4.420000e+02  4.420000e+02  4.420000e+02   
mean  -3.634285e-16  1.308343e-16 -8.045349e-16  1.281655e-16 -8.835316e-17   
std    4.761905e-02  4.761905e-02  4.761905e-02  4.761905e-02  4.761905e-02   
min   -1.072256e-01 -4.464164e-02 -9.027530e-02 -1.123996e-01 -1.267807e-01   
25%   -3.729927e-02 -4.464164e-02 -3.422907e-02 -3.665645e-02 -3.424784e-02   
50%    5.383060e-03 -4.464164e-02 -7.283766e-03 -5.670611e-03 -4.320866e-03   
75%    3.807591e-02  5.068012e-02  3.124802e-02  3.564384e-02  2.835801e-02   
max    1.107267e-01  5.068012e-02  1.705552e-01  1.320442e-01  1.539137e-01   

                 s2            s3            s4            s5            s6  
count  4.420000e+02  4.420000e+02  4.420000e+02  4.420000e+02  4.420000e+02  
mean   1.327024e-16 -4.574646e-16  3.777301e-16 -3.830854e-16 -3.412882e-16  
std    4.761905e-02  4.761905e-02  4.761905e-02  4.761905e-02  4.761905e-02  
min   -1.156131e-01 -1.023071e-01 -7.639450e-02 -1.260974e-01 -1.377672e-01  
25%   -3.035840e-02 -3.511716e-02 -3.949338e-02 -3.324879e-02 -3.317903e-02  
50%   -3.819065e-03 -6.584468e-03 -2.592262e-03 -1.947634e-03 -1.077698e-03  
75%    2.984439e-02  2.931150e-02  3.430886e-02  3.243323e-02  2.791705e-02  
max    1.987880e-01  1.811791e-01  1.852344e-01  1.335990e-01  1.356118e-01

In [19]:
diab_X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 442 entries, 0 to 441
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   age     442 non-null    float64
 1   sex     442 non-null    float64
 2   bmi     442 non-null    float64
 3   bp      442 non-null    float64
 4   s1      442 non-null    float64
 5   s2      442 non-null    float64
 6   s3      442 non-null    float64
 7   s4      442 non-null    float64
 8   s5      442 non-null    float64
 9   s6      442 non-null    float64
dtypes: float64(10)
memory usage: 34.7 KB


In [20]:
data = diab_X
data['target'] = diab_Y
data.corr()

age       sex       bmi        bp        s1        s2        s3  \
age     1.000000  0.173737  0.185085  0.335427  0.260061  0.219243 -0.075181   
sex     0.173737  1.000000  0.088161  0.241013  0.035277  0.142637 -0.379090   
bmi     0.185085  0.088161  1.000000  0.395415  0.249777  0.261170 -0.366811   
bp      0.335427  0.241013  0.395415  1.000000  0.242470  0.185558 -0.178761   
s1      0.260061  0.035277  0.249777  0.242470  1.000000  0.896663  0.051519   
s2      0.219243  0.142637  0.261170  0.185558  0.896663  1.000000 -0.196455   
s3     -0.075181 -0.379090 -0.366811 -0.178761  0.051519 -0.196455  1.000000   
s4      0.203841  0.332115  0.413807  0.257653  0.542207  0.659817 -0.738493   
s5      0.270777  0.149918  0.446159  0.393478  0.515501  0.318353 -0.398577   
s6      0.301731  0.208133  0.388680  0.390429  0.325717  0.290600 -0.273697   
target  0.187889  0.043062  0.586450  0.441484  0.212022  0.174054 -0.394789   

              s4        s5        s6    target  
age     0.203841  0.270777  0.301731  0.187889  
sex     0.332115  0.149918  0.208133  0.043062  
bmi     0.413807  0.446159  0.388680  0.586450  
bp      0.257653  0.393478  0.390429  0.441484  
s1      0.542207  0.515501  0.325717  0.212022  
s2      0.659817  0.318353  0.290600  0.174054  
s3     -0.738493 -0.398577 -0.273697 -0.394789  
s4      1.000000  0.617857  0.417212  0.430453  
s5      0.617857  1.000000  0.464670  0.565883  
s6      0.417212  0.464670  1.000000  0.382483  
target  0.430453  0.565883  0.382483  1.000000

In [21]:
X_train, X_test, y_train, y_test = train_test_split(iris_X, iris_Y, test_size = 0.2, random_state=0)
model = LinearRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
print(f'MAE : \n {MAE(y_test,y_pred)}')
print(f'MSE : {MSE(y_test,y_pred)}')
print(f'r2_score : {r2_score(y_test,y_pred)}')

MAE : 
 0.18641707995607296
MSE : 0.050923222061343205
r2_score : 0.9055032992676105


In [22]:
X_train, X_test, y_train, y_test = train_test_split(iris_X, iris_Y, test_size = 0.1, random_state=0)
model = LinearRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
print(f'MAE : \n {MAE(y_test,y_pred)}')
print(f'MSE : {MSE(y_test,y_pred)}')
print(f'r2_score : {r2_score(y_test,y_pred)}')

MAE : 
 0.21126980811548224
MSE : 0.06148029162470033
r2_score : 0.8669897536965618


зміна співвідношення призвела до погіршення резулmтату, можливо, варінт (overfitted)

In [23]:
X_train, X_test, y_train, y_test = train_test_split(iris_X, iris_Y, test_size = 0.3, random_state=0)
model = LinearRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
print(f'MAE : \n {MAE(y_test,y_pred)}')
print(f'MSE : {MSE(y_test,y_pred)}')
print(f'r2_score : {r2_score(y_test,y_pred)}')

MAE : 
 0.19781443339791976
MSE : 0.058867619212325216
r2_score : 0.8998261101639004


In [24]:
X_train, X_test, y_train, y_test = train_test_split(iris_X, iris_Y, test_size = 0.5, random_state=0)
model = LinearRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
print(f'MAE : \n {MAE(y_test,y_pred)}')
print(f'MSE : {MSE(y_test,y_pred)}')
print(f'r2_score : {r2_score(y_test,y_pred)}')

MAE : 
 0.20236571922608163
MSE : 0.06391522366710366
r2_score : 0.8931898000215514


зміна співвідношення до меншої тестової вибірки призвела теж до погіршення результату, але менш вираженного, можливо, варінfт underfitted